// Code generated by "stringer -type=RegName"; DO NOT EDIT

package registers

import "fmt"

const _RegName_name = "ModelNumberFirmwareVersionServoIDBaudRateReturnDelayTimeCwAngleLimitCcwAngleLimitHighestLimitTemperatureLowestLimitVoltageHighestLimitVoltageMaxTorqueStatusReturnLevelAlarmLedAlarmShutdownTorqueEnableLedCwComplianceMarginCcwComplianceMarginCwComplianceSlopeCcwComplianceSlopeGoalPositionMovingSpeedTorqueLimitPresentPositionPresentSpeedPresentLoadPresentVoltagePresentTemperatureRegisteredMovingLockPunch"

var _RegName_index = [...]uint16{0, 11, 26, 33, 41, 56, 68, 81, 104, 122, 141, 150, 167, 175, 188, 200, 203, 221, 240, 257, 275, 287, 298, 309, 324, 336, 347, 361, 379, 389, 395, 399, 404}

func (i RegName) String() string {
	if i < 0 || i >= RegName(len(_RegName_index)-1) {
		return fmt.Sprintf("RegName(%d)", i)
	}
	return _RegName_name[_RegName_index[i]:_RegName_index[i+1]]
}
